export const categoriesIni = [
    {
        name: "България",
        path: "/news/category/bulgaria",
        primary: true,
        secondary: false,
        important: true,
    },
    {
        name: "Свят",
        path: "/news/category/world",
        primary: true,
        secondary: false,
        important: true,
    },
    {
        name: "Политика",
        path: "/news/category/politics",
        primary: true,
        secondary: false,
        important: true,
    },
    {
        name: "Икономика",
        path: "/news/category/economy",
        primary: true,
        secondary: false,
        important: true,
    },
    {
        name: "Криминални",
        path: "/news/category/crime",
        primary: true,
        secondary: false,
        important: true,
    },
    {
        name: "Спорт",
        path: "/news/category/sport",
        primary: true,
        secondary: false,
        important: true,
    },
    {
        name: "Авто",
        path: "/news/category/auto",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Технологии",
        path: "/news/category/technology",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Наука",
        path: "/news/category/science",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Анализи",
        path: "/news/category/analysis",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Интервюта",
        path: "/news/category/interview",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Мнения",
        path: "/news/category/opinion",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Култура",
        path: "/news/category/culture",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Образование",
        path: "/news/category/education",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Семейство",
        path: "/news/category/family",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Любопитно",
        path: "/news/category/love",
        primary: false,
        secondary: true,
        important: false,
    },
];
