export const categoriesIni = [
    {
        name: "България",
        path: "/news/bulgaria",
        primary: true,
        secondary: false,
        important: true,
    },
    {
        name: "Свят",
        path: "/news/world",
        primary: true,
        secondary: false,
        important: true,
    },
    {
        name: "Политика",
        path: "/news/politics",
        primary: true,
        secondary: false,
        important: true,
    },
    {
        name: "Икономика",
        path: "/news/economy",
        primary: true,
        secondary: false,
        important: true,
    },
    {
        name: "Криминални",
        path: "/news/crime",
        primary: true,
        secondary: false,
        important: true,
    },
    {
        name: "Спорт",
        path: "/news/sport",
        primary: true,
        secondary: false,
        important: true,
    },
    {
        name: "Авто",
        path: "/news/auto",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Технологии",
        path: "/news/technology",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Наука",
        path: "/news/science",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Анализи",
        path: "/news/analysis",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Интервюта",
        path: "/news/interview",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Мнения",
        path: "/news/opinion",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Култура",
        path: "/news/culture",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Образование",
        path: "/news/education",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Семейство",
        path: "/news/family",
        primary: false,
        secondary: true,
        important: false,
    },
    {
        name: "Любопитно",
        path: "/news/love",
        primary: false,
        secondary: true,
        important: false,
    },
];
